package com.cs.backend.db.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_area.id
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_area.areaName
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_area.describle
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    private String describle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_area.isDeleted
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_area.id
     *
     * @return the value of cs_area.id
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_area.id
     *
     * @param id the value for cs_area.id
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_area.areaName
     *
     * @return the value of cs_area.areaName
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_area.areaName
     *
     * @param areaName the value for cs_area.areaName
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_area.describle
     *
     * @return the value of cs_area.describle
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public String getDescrible() {
        return describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_area.describle
     *
     * @param describle the value for cs_area.describle
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public void setDescrible(String describle) {
        this.describle = describle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_area.isDeleted
     *
     * @return the value of cs_area.isDeleted
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_area.isDeleted
     *
     * @param isDeleted the value for cs_area.isDeleted
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}