package com.cs.backend.db.model;

public class Operatelog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.id
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.userId
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.userIp
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private String userIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.actionName
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private String actionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.method
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private String method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.result
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private Integer result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.modifyTime
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private Long modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.isDeleted
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.describle
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private String describle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_operatelog.parameters
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	private String parameters;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.id
	 * @return  the value of cs_operatelog.id
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.id
	 * @param id  the value for cs_operatelog.id
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.userId
	 * @return  the value of cs_operatelog.userId
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.userId
	 * @param userId  the value for cs_operatelog.userId
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.userIp
	 * @return  the value of cs_operatelog.userIp
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public String getUserIp() {
		return userIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.userIp
	 * @param userIp  the value for cs_operatelog.userIp
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.actionName
	 * @return  the value of cs_operatelog.actionName
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public String getActionName() {
		return actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.actionName
	 * @param actionName  the value for cs_operatelog.actionName
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.method
	 * @return  the value of cs_operatelog.method
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.method
	 * @param method  the value for cs_operatelog.method
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.result
	 * @return  the value of cs_operatelog.result
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public Integer getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.result
	 * @param result  the value for cs_operatelog.result
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setResult(Integer result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.modifyTime
	 * @return  the value of cs_operatelog.modifyTime
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public Long getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.modifyTime
	 * @param modifyTime  the value for cs_operatelog.modifyTime
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setModifyTime(Long modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.isDeleted
	 * @return  the value of cs_operatelog.isDeleted
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.isDeleted
	 * @param isDeleted  the value for cs_operatelog.isDeleted
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.describle
	 * @return  the value of cs_operatelog.describle
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public String getDescrible() {
		return describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.describle
	 * @param describle  the value for cs_operatelog.describle
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setDescrible(String describle) {
		this.describle = describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_operatelog.parameters
	 * @return  the value of cs_operatelog.parameters
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public String getParameters() {
		return parameters;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_operatelog.parameters
	 * @param parameters  the value for cs_operatelog.parameters
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	public void setParameters(String parameters) {
		this.parameters = parameters;
	}
}