package com.cs.backend.db.model;

import java.io.Serializable;

public class User implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.userId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.userName
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.passWord
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private String passWord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.isDeleted
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.roleId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.platformId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private Integer platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_user.model
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	private String model;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.userId
	 * @return  the value of cs_user.userId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.userId
	 * @param userId  the value for cs_user.userId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.userName
	 * @return  the value of cs_user.userName
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.userName
	 * @param userName  the value for cs_user.userName
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.passWord
	 * @return  the value of cs_user.passWord
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public String getPassWord() {
		return passWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.passWord
	 * @param passWord  the value for cs_user.passWord
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.isDeleted
	 * @return  the value of cs_user.isDeleted
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.isDeleted
	 * @param isDeleted  the value for cs_user.isDeleted
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.roleId
	 * @return  the value of cs_user.roleId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.roleId
	 * @param roleId  the value for cs_user.roleId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.platformId
	 * @return  the value of cs_user.platformId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public Integer getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.platformId
	 * @param platformId  the value for cs_user.platformId
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_user.model
	 * @return  the value of cs_user.model
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_user.model
	 * @param model  the value for cs_user.model
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	public void setModel(String model) {
		this.model = model;
	}

	private static final long serialVersionUID = -2787313511143049548L;
}