package com.cs.backend.db.model;

public class GameLogDB {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.id
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.platformId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.serverId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.serverName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.platformName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String platformName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.dbip
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String dbip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.dbport
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer dbport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.dbName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String dbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.dbUsername
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String dbUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.dbPassword
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private String dbPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.createTime
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.isDeleted
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_gamelogdb.sid
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	private Integer sid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.id
	 * @return  the value of cs_gamelogdb.id
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.id
	 * @param id  the value for cs_gamelogdb.id
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.platformId
	 * @return  the value of cs_gamelogdb.platformId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.platformId
	 * @param platformId  the value for cs_gamelogdb.platformId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.serverId
	 * @return  the value of cs_gamelogdb.serverId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.serverId
	 * @param serverId  the value for cs_gamelogdb.serverId
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.serverName
	 * @return  the value of cs_gamelogdb.serverName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.serverName
	 * @param serverName  the value for cs_gamelogdb.serverName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.platformName
	 * @return  the value of cs_gamelogdb.platformName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getPlatformName() {
		return platformName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.platformName
	 * @param platformName  the value for cs_gamelogdb.platformName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setPlatformName(String platformName) {
		this.platformName = platformName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.dbip
	 * @return  the value of cs_gamelogdb.dbip
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getDbip() {
		return dbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.dbip
	 * @param dbip  the value for cs_gamelogdb.dbip
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setDbip(String dbip) {
		this.dbip = dbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.dbport
	 * @return  the value of cs_gamelogdb.dbport
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getDbport() {
		return dbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.dbport
	 * @param dbport  the value for cs_gamelogdb.dbport
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setDbport(Integer dbport) {
		this.dbport = dbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.dbName
	 * @return  the value of cs_gamelogdb.dbName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getDbName() {
		return dbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.dbName
	 * @param dbName  the value for cs_gamelogdb.dbName
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.dbUsername
	 * @return  the value of cs_gamelogdb.dbUsername
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getDbUsername() {
		return dbUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.dbUsername
	 * @param dbUsername  the value for cs_gamelogdb.dbUsername
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setDbUsername(String dbUsername) {
		this.dbUsername = dbUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.dbPassword
	 * @return  the value of cs_gamelogdb.dbPassword
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public String getDbPassword() {
		return dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.dbPassword
	 * @param dbPassword  the value for cs_gamelogdb.dbPassword
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setDbPassword(String dbPassword) {
		this.dbPassword = dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.createTime
	 * @return  the value of cs_gamelogdb.createTime
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.createTime
	 * @param createTime  the value for cs_gamelogdb.createTime
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.isDeleted
	 * @return  the value of cs_gamelogdb.isDeleted
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.isDeleted
	 * @param isDeleted  the value for cs_gamelogdb.isDeleted
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_gamelogdb.sid
	 * @return  the value of cs_gamelogdb.sid
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_gamelogdb.sid
	 * @param sid  the value for cs_gamelogdb.sid
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}
}