package com.cs.backend.db.model;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.id
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.menuName
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.menuUrl
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private String menuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.describle
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private String describle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.isDeleted
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.type
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_menu.icon
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	private String icon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.id
	 * @return  the value of cs_menu.id
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.id
	 * @param id  the value for cs_menu.id
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.menuName
	 * @return  the value of cs_menu.menuName
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.menuName
	 * @param menuName  the value for cs_menu.menuName
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.menuUrl
	 * @return  the value of cs_menu.menuUrl
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.menuUrl
	 * @param menuUrl  the value for cs_menu.menuUrl
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.describle
	 * @return  the value of cs_menu.describle
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public String getDescrible() {
		return describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.describle
	 * @param describle  the value for cs_menu.describle
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setDescrible(String describle) {
		this.describle = describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.isDeleted
	 * @return  the value of cs_menu.isDeleted
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.isDeleted
	 * @param isDeleted  the value for cs_menu.isDeleted
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.type
	 * @return  the value of cs_menu.type
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.type
	 * @param type  the value for cs_menu.type
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_menu.icon
	 * @return  the value of cs_menu.icon
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_menu.icon
	 * @param icon  the value for cs_menu.icon
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}
}