package com.cs.backend.db.model;

public class Platform {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.platformId
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private Integer platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.platformName
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private String platformName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.platformRight
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private String platformRight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.isDeleted
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.exchangeRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private Integer exchangeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.describle
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private String describle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_platform.realRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	private Integer realRate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.platformId
	 * @return  the value of cs_platform.platformId
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public Integer getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.platformId
	 * @param platformId  the value for cs_platform.platformId
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.platformName
	 * @return  the value of cs_platform.platformName
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public String getPlatformName() {
		return platformName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.platformName
	 * @param platformName  the value for cs_platform.platformName
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setPlatformName(String platformName) {
		this.platformName = platformName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.platformRight
	 * @return  the value of cs_platform.platformRight
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public String getPlatformRight() {
		return platformRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.platformRight
	 * @param platformRight  the value for cs_platform.platformRight
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setPlatformRight(String platformRight) {
		this.platformRight = platformRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.isDeleted
	 * @return  the value of cs_platform.isDeleted
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.isDeleted
	 * @param isDeleted  the value for cs_platform.isDeleted
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.exchangeRate
	 * @return  the value of cs_platform.exchangeRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public Integer getExchangeRate() {
		return exchangeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.exchangeRate
	 * @param exchangeRate  the value for cs_platform.exchangeRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setExchangeRate(Integer exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.describle
	 * @return  the value of cs_platform.describle
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public String getDescrible() {
		return describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.describle
	 * @param describle  the value for cs_platform.describle
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setDescrible(String describle) {
		this.describle = describle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_platform.realRate
	 * @return  the value of cs_platform.realRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public Integer getRealRate() {
		return realRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_platform.realRate
	 * @param realRate  the value for cs_platform.realRate
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	public void setRealRate(Integer realRate) {
		this.realRate = realRate;
	}
}