package com.cs.backend.db.model;

public class ROLE_MENUKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_rolemenu.menuId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    private Integer menuId = null;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_rolemenu.roleId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    private Integer roleId = null;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_rolemenu.menuId
     *
     * @return the value of cs_rolemenu.menuId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_rolemenu.menuId
     *
     * @param menuId the value for cs_rolemenu.menuId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_rolemenu.roleId
     *
     * @return the value of cs_rolemenu.roleId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_rolemenu.roleId
     *
     * @param roleId the value for cs_rolemenu.roleId
     *
     * @mbggenerated Tue Jun 24 13:36:57 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}