package com.cs.backend.db.model;

public class Server {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.id
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.serverName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.areaId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.areaName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.isDeleted
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.openTime
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Long openTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.gamedbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String gamedbip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.gamedbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer gamedbport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.socketPort
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer socketPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.logdbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String logdbip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.logdbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer logdbport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.dbPassword
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String dbPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.gamedbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String gamedbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.logdbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String logdbName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.dbUsername
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String dbUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.serverIp
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private String serverIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_server.serverId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	private Integer serverId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.id
	 * @return  the value of cs_server.id
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.id
	 * @param id  the value for cs_server.id
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.serverName
	 * @return  the value of cs_server.serverName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.serverName
	 * @param serverName  the value for cs_server.serverName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.areaId
	 * @return  the value of cs_server.areaId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.areaId
	 * @param areaId  the value for cs_server.areaId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.areaName
	 * @return  the value of cs_server.areaName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.areaName
	 * @param areaName  the value for cs_server.areaName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.isDeleted
	 * @return  the value of cs_server.isDeleted
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.isDeleted
	 * @param isDeleted  the value for cs_server.isDeleted
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.openTime
	 * @return  the value of cs_server.openTime
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Long getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.openTime
	 * @param openTime  the value for cs_server.openTime
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setOpenTime(Long openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.gamedbip
	 * @return  the value of cs_server.gamedbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getGamedbip() {
		return gamedbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.gamedbip
	 * @param gamedbip  the value for cs_server.gamedbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setGamedbip(String gamedbip) {
		this.gamedbip = gamedbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.gamedbport
	 * @return  the value of cs_server.gamedbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getGamedbport() {
		return gamedbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.gamedbport
	 * @param gamedbport  the value for cs_server.gamedbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setGamedbport(Integer gamedbport) {
		this.gamedbport = gamedbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.socketPort
	 * @return  the value of cs_server.socketPort
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getSocketPort() {
		return socketPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.socketPort
	 * @param socketPort  the value for cs_server.socketPort
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setSocketPort(Integer socketPort) {
		this.socketPort = socketPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.logdbip
	 * @return  the value of cs_server.logdbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getLogdbip() {
		return logdbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.logdbip
	 * @param logdbip  the value for cs_server.logdbip
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setLogdbip(String logdbip) {
		this.logdbip = logdbip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.logdbport
	 * @return  the value of cs_server.logdbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getLogdbport() {
		return logdbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.logdbport
	 * @param logdbport  the value for cs_server.logdbport
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setLogdbport(Integer logdbport) {
		this.logdbport = logdbport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.dbPassword
	 * @return  the value of cs_server.dbPassword
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getDbPassword() {
		return dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.dbPassword
	 * @param dbPassword  the value for cs_server.dbPassword
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setDbPassword(String dbPassword) {
		this.dbPassword = dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.gamedbName
	 * @return  the value of cs_server.gamedbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getGamedbName() {
		return gamedbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.gamedbName
	 * @param gamedbName  the value for cs_server.gamedbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setGamedbName(String gamedbName) {
		this.gamedbName = gamedbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.logdbName
	 * @return  the value of cs_server.logdbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getLogdbName() {
		return logdbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.logdbName
	 * @param logdbName  the value for cs_server.logdbName
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setLogdbName(String logdbName) {
		this.logdbName = logdbName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.dbUsername
	 * @return  the value of cs_server.dbUsername
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getDbUsername() {
		return dbUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.dbUsername
	 * @param dbUsername  the value for cs_server.dbUsername
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setDbUsername(String dbUsername) {
		this.dbUsername = dbUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.serverIp
	 * @return  the value of cs_server.serverIp
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public String getServerIp() {
		return serverIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.serverIp
	 * @param serverIp  the value for cs_server.serverIp
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_server.serverId
	 * @return  the value of cs_server.serverId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_server.serverId
	 * @param serverId  the value for cs_server.serverId
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}
}