package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.GameLogDB;

public interface GameLogDBMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	int insert(GameLogDB record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	int insertSelective(GameLogDB record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	GameLogDB selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	int updateByPrimaryKeySelective(GameLogDB record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_gamelogdb
	 * @mbggenerated  Fri Jul 25 15:15:26 CST 2014
	 */
	int updateByPrimaryKey(GameLogDB record);

	List<GameLogDB> selectGameLogDBBySid(int sid) ;
}