package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.Menu;

public interface MenuMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	Menu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_menu
	 * @mbggenerated  Thu Aug 07 15:38:59 CST 2014
	 */
	int updateByPrimaryKey(Menu record);

	/**
     * 	查询�?��的菜�?
     */
    List<Menu> selectAllMenu() ;
    
    /**
     * 查询文件�?
     */
    List<Menu> selectDirMenu() ;
    
    /**
     * 分页
     * @param pageList 
     */
    List<Menu> queryByPage();
    
    /**
     * 根据父级菜单查找�?��菜单
     * @param type
     * @return
     */
	List<Menu> selectMenuByType(int type);

	/**
     * 根据条件查找�?��菜单 模糊查询
     * @param type
     * @return
     */
	List<Menu> selectMenuByXX(Menu record);

	/**
     * 根据条件查找�?��菜单
     * @param type
     * @return
     */
	List<Menu> selectMenuByXXPrecise(Menu record);

	/**
     * 根据目录名查找目录
     * @param type
     * @return
     */
	Menu selectMenuByName(String menuName);
}