package com.cs.backend.db.dao;

import com.cs.backend.db.model.Operatelog;

public interface OperatelogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int insert(Operatelog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int insertSelective(Operatelog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	Operatelog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int updateByPrimaryKeySelective(Operatelog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(Operatelog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_operatelog
	 * @mbggenerated  Wed Sep 17 12:46:15 CST 2014
	 */
	int updateByPrimaryKey(Operatelog record);
}