package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.User;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_user
	 * @mbggenerated  Tue Sep 09 11:47:49 CST 2014
	 */
	int updateByPrimaryKey(User record);

	/**
     * 根据用户名找到用户信�?    * @param  userName
    * @return User    返回用户信息
    * @throws
     */
    User selectUserByName(String userName);

    /**
     * 	查询�?��的用�?     */
	List<User> selectAllUser();
	
	/**
	 * 根据角色id查找用户
	 * @param roleId
	 * @return
	 */
	List<User> selectUserByRoleId(int roleId);

	/**
	 * 根据条件查找用户 模糊查询
	 */
	List<User> selectUserByXX(User record);

	/**
	 * 根据条件查找用户
	 */
	List<User> selectUserByXXPrecise(User record);
	
}