package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.Area;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_area
     *
     * @mbggenerated Wed Sep 17 09:33:12 CST 2014
     */
    int updateByPrimaryKey(Area record);
    
    List<Area> selectAllAreasWithoutDeleted() ;
}