package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.Platform;

public interface PlatformMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	int deleteByPrimaryKey(Integer platformId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	int insert(Platform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	int insertSelective(Platform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	Platform selectByPrimaryKey(Integer platformId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	int updateByPrimaryKeySelective(Platform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_platform
	 * @mbggenerated  Tue Sep 09 11:52:42 CST 2014
	 */
	int updateByPrimaryKey(Platform record);

	List<Platform> selectAllPlatform() ;

	List<Platform> selectPlatformByXX(Platform record);

	List<Platform> selectPlatformByXXPrecise(Platform record);

	Platform selectPlatformByName(String platformName);
}