package com.cs.backend.db.dao;

import java.util.List;

import com.cs.backend.db.model.Server;

public interface ServerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	int insert(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	int insertSelective(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	Server selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	int updateByPrimaryKeySelective(Server record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_server
	 * @mbggenerated  Wed Sep 17 09:31:46 CST 2014
	 */
	int updateByPrimaryKey(Server record);

	/**
	 * 根据平台id，区服id找到指定区服
	 */
	Server getServerListByAreaIdServerId(Server record) ;
	
	/**
	 * 根据平台id找到指定平台的所有区�?	 */
	List<Server> getServerListByAreaId(int platformId) ;
	
	/**
	 * 查询�?��的区�?
	 */
	List<Server> getAllServerList() ;

	/**
	 * 按条件模糊查�?
	 * @param server 
	 * @return
	 */
	List<Server> selectServerByXX(Server server);
}